name: Basic one
on: workflow_dispatch
jobs:
  first_job:
    runs-on:  ubuntu-latest
    steps:
      - name: printing hello world.
        run: |
          echo "hello bro"
          echo "and everyone"
      - name: printing wishes
        run: echo "good morning"
