name: first_one
on:
  push:
     branches: [ "main" ]
jobs:
  first_one:
    runs-on: ubuntu-latest
    steps:
      - name: printing greetings
        run: echo "hello world"
  output:
    runs-on: ubuntu-latest
    steps:
      - name: printing the github context
        run: echo "${{ toJSON(github) }}"

  third_one:
    runs-on: ubuntu-latest
    steps:
      - name: printing greetings
        run: echo "checking for all"

  fourth_one:
    runs-on: ubuntu-latest
    steps:
      - name: printing greetings
        run: echo "checking for all"

  fifth_one:
    runs-on: ubuntu-latest
    steps:
      - name: printing greetings
        run: echo "checking for all"
