name: second_one
on: push
jobs:
  project:
    runs-on: ubuntu-latest
    steps:
      - name: checking out the code
        uses: actions/checkout@v3
      - name: installing dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: installing dependcies
        run: npm ci
      - name: testing
        run: npm test
  
  deploy:
    needs: project
    runs-on: ubuntu-latest
    steps:
      - name: checking out the code
        uses: actions/checkout@v3
      - name: installing node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: installing dependencies
        run: npm ci
      - name: buildind the code
        run: npm run build
      - name: deploying
        run: echo "deployed interstellar"
